ICONEXT/Models/employee.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.ComponentModel.DataAnnotations;

namespace ICONEXT.Models
{
    public class employee
    {
        public string ID { get; set; }

        public string Title { get; set; }

        public string Name { get; set; }

        public string Surname { get; set; }

        public string Nickname { get; set; }

        public string Position { get; set; }

        public string StartDate { get; set; }

        public string EndDate { get; set; }

        public string Tel { get; set; }

        public string Email { get; set; }

        public string Active { get; set; }
    }
}

ICONEXT/Controllers/employeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICONEXT.Data;
using ICONEXT.Models;

namespace ICONEXT.Controllers
{
    public class employeesController : Controller
    {
        private readonly ICONEXTContext _context;

        public employeesController(ICONEXTContext context)
        {
            _context = context;
        }

        // GET: employees
        public async Task<IActionResult> Index()
        {
            return View(await _context.employee.ToListAsync());
        }

        // GET: employees/Details/5
        public async Task<IActionResult> Details(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.employee
                .FirstOrDefaultAsync(m => m.ID == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Name,Surname,Nickname,Position,StartDate,EndDate,Tel,Email,Active")] employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: employees/Edit/5
        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.employee.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ID,Title,Name,Surname,Nickname,Position,StartDate,EndDate,Tel,Email,Active")] employee employee)
        {
            if (id != employee.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!employeeExists(employee.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: employees/Delete/5
        public async Task<IActionResult> Delete(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.employee
                .FirstOrDefaultAsync(m => m.ID == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var employee = await _context.employee.FindAsync(id);
            _context.employee.Remove(employee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool employeeExists(string id)
        {
            return _context.employee.Any(e => e.ID == id);
        }
    }
}

ICONEXT/Controllers/outsourcesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICONEXT.Data;
using ICONEXT.Models;

namespace ICONEXT.Controllers
{
    public class outsourcesController : Controller
    {
        private readonly ICONEXTContext _context;

        public outsourcesController(ICONEXTContext context)
        {
            _context = context;
        }

        // GET: outsources
        public async Task<IActionResult> Index()
        {
            return View(await _context.outsource.ToListAsync());
        }

        // GET: outsources/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var outsource = await _context.outsource
                .FirstOrDefaultAsync(m => m.ID == id);
            if (outsource == null)
            {
                return NotFound();
            }

            return View(outsource);
        }

        // GET: outsources/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: outsources/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Name,Surname,Nickname,Position,StartDate,EndDate,Tel,Email,Active")] outsource outsource)
        {
            if (ModelState.IsValid)
            {
                _context.Add(outsource);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(outsource);
        }

        // GET: outsources/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var outsource = await _context.outsource.FindAsync(id);
            if (outsource == null)
            {
                return NotFound();
            }
            return View(outsource);
        }

        // POST: outsources/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ID,Title,Name,Surname,Nickname,Position,StartDate,EndDate,Tel,Email,Active")] outsource outsource)
        {
            if (id != outsource.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(outsource);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!outsourceExists(outsource.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(outsource);
        }

        // GET: outsources/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var outsource = await _context.outsource
                .FirstOrDefaultAsync(m => m.ID == id);
            if (outsource == null)
            {
                return NotFound();
            }

            return View(outsource);
        }

        // POST: outsources/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var outsource = await _context.outsource.FindAsync(id);
            _context.outsource.Remove(outsource);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool outsourceExists(string id)
        {
            return _context.outsource.Any(e => e.ID == id);
        }
    }
}

ICONEXT/Views/employees/Create.cshtml
@model ICONEXT.Models.employee

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Add Staff</h1>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

             <div class="form-group">
        <label asp-for="ID" class="control-label"></label>
        <input asp-for="ID" autocomplete="off" class="form-control" />
        <span asp-validation-for="ID" class="text-danger"></span>
    </div>
    

             <div class="form-group ">
                 <label asp-for="Title" class="control-label"></label>

                 <select asp-for="Title" class="custom-select">
                     <option selected disabled>Choose Title</option>
                     <option value="Mr.">Mr.</option>
                     <option value="Mrs.">Mrs.</option>
                     <option value="Miss">Miss</option>
                     <option value="Dr.">Dr.</option>
                 </select>
                 <span asp-validation-for="Title" class="text-danger"></span>
             </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" autocomplete="off" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" autocomplete="off" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nickname" class="control-label"></label>
                <input asp-for="Nickname" autocomplete="off" class="form-control" />
                <span asp-validation-for="Nickname" class="text-danger"></span>
            </div>


            <div class="form-group ">
                <label asp-for="Position" class="control-label"></label>

                <select asp-for="Position" class="custom-select">
                    <option selected disabled>Choose Position</option>
                    <option value="Group Manager">Group Manager</option>
                    <option value="Group Leader">Group Leader</option>
                    <option value="System Analyst">System Analyst</option>
                    <option value="Programmer">Programmer</option>
                    <option value="Quality Assurance">Quality Assurance</option>
                </select>
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" autocomplete="off" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" autocomplete="off" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group row">
                <label asp-for="StartDate" for="example-date-input" class="col-4 col-form-label">Start Date</label>
                <div class="col-10">
                    <input asp-for="StartDate" class="form-control" type="date"  id="example-date-input">
                </div>
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>



            <div class="form-group row">
                <label asp-for="EndDate" for="example-date-input" class="col-4 col-form-label">End Date</label>
                <div class="col-10">
                    <input asp-for="EndDate" class="form-control" type="date" id="example-date-input">
                </div>
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>



            <div class="form-group">
                <a>Active :</a>&nbsp;
                <input type="radio" asp-for="Active" value="Y"><label asp-for="Active" class="radio-inline">&nbsp;Yes</label>&nbsp;
                <input type="radio" asp-for="Active" value="N"><label asp-for="Active" class="radio-inline">&nbsp;No</label>
                <span asp-validation-for="Active" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Confrim" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }

       

ICONEXT/Views/employees/Delete.cshtml
@model ICONEXT.Models.employee


@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1>Delete Staff</h1>
</div>
<h3>Are you sure you want to delete this?</h3>
<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nickname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nickname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tel)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ICONEXT/Views/employees/Details.cshtml
@model ICONEXT.Models.employee

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1>Details Staff</h1>
</div>


<div class="card  col-7">

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nickname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nickname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tel)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
    </dl>
</div>

<div class="text-center">
    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ICONEXT/Views/employees/Edit.cshtml
@model ICONEXT.Models.employee

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit staff</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            

            <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" autocomplete="off" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>

            <div class="form-group ">
                <label asp-for="Title" class="control-label"></label>

                <select asp-for="Title" class="custom-select">
                    <option selected disabled>Choose Title</option>
                    <option value="Mr.">Mr.</option>
                    <option value="Mrs.">Mrs.</option>
                    <option value="Miss">Miss</option>
                    <option value="Dr.">Dr.</option>
                </select>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" autocomplete="off" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" autocomplete="off" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nickname" class="control-label"></label>
                <input asp-for="Nickname" autocomplete="off" class="form-control" />
                <span asp-validation-for="Nickname" class="text-danger"></span>
            </div>
            <div class="form-group ">
                <label asp-for="Position" class="control-label"></label>

                <select asp-for="Position" class="custom-select">
                    <option selected disabled>Choose Position</option>
                    <option value="Group Manager">Group Manager</option>
                    <option value="Group Leader">Group Leader</option>
                    <option value="System Analyst">System Analyst</option>
                    <option value="Programmer">Programmer</option>
                    <option value="Quality Assurance">Quality Assurance</option>
                </select>
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" autocomplete="off" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" autocomplete="off" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group row">
                <label asp-for="StartDate" for="example-date-input" class="col-4 col-form-label">Start Date</label>
                <div class="col-10">
                    <input asp-for="StartDate" class="form-control" type="date"  id="example-date-input">
                </div>
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>



            <div class="form-group row">
                <label asp-for="EndDate" for="example-date-input" class="col-4 col-form-label">End Date</label>
                <div class="col-10">
                    <input asp-for="EndDate" class="form-control" type="date"  id="example-date-input">
                </div>
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>


            <div class="form-group">
                <a>Active :</a>&nbsp;
                <input type="radio" asp-for="Active" value="Y"><label asp-for="Active" class="radio-inline">&nbsp;Yes</label>&nbsp;
                <input type="radio" asp-for="Active" value="N"><label asp-for="Active" class="radio-inline">&nbsp;No</label>
                <span asp-validation-for="Active" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ICONEXT/Views/employees/Index.cshtml
@model IEnumerable<ICONEXT.Models.employee>

 

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}

<h1 id="title">Full time staff</h1>
<br>

<div class="text-center">
    <div class="row">
        <div class="col-3">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        </div>
        <div class="col-5">
            <div class="text-left">
                <button class="btn btn-outline-success my-2 my-sm-0" id="Search">Search</button>
            </div>

        </div>

        

        <div class="dropdown col-4">
            <button class="btn btn-warning dropdown-toggle" type="button" data-toggle="dropdown">
                Select type
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li><a asp-controller="employees" asp-action="Index">Full time staff</a></li>
                <li><a asp-controller="outsources" asp-action="Index">Outsource</a></li>
                
            </ul>
        </div>

    </div>
</div>
<br>


<p>
    <div style="text-align:right">
        <a asp-action="Create">
            <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-person-plus-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm7.5-3a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z" />
            </svg>
        </a>
    </div>
</p>

    <table class="table table-striped table-primary">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Surname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nickname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Position)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tel)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.StartDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EndDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Active)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody id="TableFT">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Surname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nickname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Position)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tel)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Active)
                    </td>
                    
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                        </td>
                    
                </tr>
            }
        </tbody>

    </table>