ICONEXT/Models/project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace ICONEXT.Models
{
    public class project
    {
        [Key]
        public int ProjID { get; set; }
        public string Name { get; set; }
        public string Partner { get; set; }
        public string Customer { get; set; }
        public string StartDate { get; set; }

        
    }
}

ICONEXT/Controllers/Project_PhaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data;
using Microsoft.Data.SqlClient;
using ICONEXT.Models;

using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICONEXT.Data;
using System.Collections;
using Microsoft.AspNetCore.Builder;






namespace ICONEXT.Controllers
{
    public class Project_PhaseController : Controller
    {

        private readonly ICONEXTContext _context;

        public Project_PhaseController(ICONEXTContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            ViewData["Results"] = TablesColumnsDisplay();
            return View();
        }


        public IActionResult ViewProject()
        {
            ViewData["Results"] = TablesColumnsDisplay();
            return View();
        }


        [HttpPost]

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ViewProject([Bind("Tasks,Phase,FromDate,EndDate,Usage")] Project_Phase Project_Phase)
        {
            if (ModelState.IsValid)
            {
                _context.Add(Project_Phase);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(Project_Phase);
        }





        ///// <Database>/////

        public static List<Project_Phase> TablesColumnsDisplay()
        {
            List<Project_Phase> PP = new List<Project_Phase>();
            string connection = "Data Source=(localdb)\\mssqllocaldb;Initial Catalog=ICONEXTContext-1;Integrated Security=True";

            using (SqlConnection sqlconn = new SqlConnection(connection))
            {
                using (SqlCommand sqlcomm = new SqlCommand("select project.Name, project.Partner, project.Customer,project.StartDate, TaskProject.Tasks, PhaseProject.Phase, PhaseProject.FromDate, PhaseProject.EndDate, PhaseProject.Usage from project full join TaskProject on project.ProjID=TaskProject.ProjID full join PhaseProject on TaskProject.TID=PhaseProject.TID "))
                {
                    using (SqlDataAdapter SDA = new SqlDataAdapter())
                    {
                        sqlcomm.Connection = sqlconn;
                        sqlconn.Open();
                        SDA.SelectCommand = sqlcomm;

                        SqlDataReader SDR = sqlcomm.ExecuteReader();
                        while (SDR.Read())
                        {
                            Project_Phase PPOBJ = new Project_Phase();
                            PPOBJ.Name = SDR["Name"].ToString();
                            PPOBJ.Tasks = SDR["Tasks"].ToString();
                            PPOBJ.Partner = SDR["Partner"].ToString();
                            PPOBJ.Customer = SDR["Customer"].ToString();
                            PPOBJ.StartDate = SDR["StartDate"].ToString();
                            PPOBJ.Phase = SDR["Phase"].ToString();
                            PPOBJ.FromDate = SDR["FromDate"].ToString();
                            PPOBJ.EndDate = SDR["EndDate"].ToString();
                            PPOBJ.Usage = SDR["Usage"].ToString();

                            PP.Add(PPOBJ);

                        }
                    }
                    return PP;
                }
            }
        }
    }
}

ICONEXT/Controllers/projectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICONEXT.Data;
using ICONEXT.Models;
using System.Collections;
using Microsoft.AspNetCore.Builder;

namespace ICONEXT.Controllers
{
    public class projectsController : Controller
    {
        private readonly ICONEXTContext _context;

        public projectsController(ICONEXTContext context)
        {
            _context = context;
        }

        // GET: projects
         public async Task<IActionResult> Index()
        {
          return View(await _context.project.ToListAsync());
        }

        
      
        public IActionResult ViewProject()
        {
            return View();
        }


       


        public IActionResult Overview()
        {
            return View();
        }




        // GET: projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.project
                .FirstOrDefaultAsync(m => m.ProjID == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: projects/Create

        
        public IActionResult Create()
        {
            return View();
        }

        // POST: projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
 

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProjID,Name,Partner,Customer,StartDate")] project project)
        {
            if (ModelState.IsValid)
            {
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.project.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        /*[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ViewProject([Bind("TID,Tasks")] project TaskProject)
        {
            
            if (ModelState.IsValid)
            {
                _context.Add(TaskProject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ViewProject));
            }
            return View(TaskProject);
        }
        */
   
        // POST: projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProjID,Name,Partner,Customer,StartDate")] project project)
        {
            if (id != project.ProjID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!projectExists(project.ProjID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: projects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.project
                .FirstOrDefaultAsync(m => m.ProjID == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var project = await _context.project.FindAsync(id);
            _context.project.Remove(project);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool projectExists(int id)
        {
            return _context.project.Any(e => e.ProjID == id);
        }
        
           
        }

}

ICONEXT/Views/projects/Create.cshtml
@model ICONEXT.Models.project

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1>New Project</h1>
</div>

    <hr />
    
        <div class="row ">
            <div class=" col-md-6">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="ProjID" class="control-label"></label>
                        <input asp-for="ProjID" autocomplete="off" class="form-control" />
                        <span asp-validation-for="ProjID" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" autocomplete="off" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Partner" class="control-label"></label>
                        <input asp-for="Partner"  class="form-control" />
                        <span asp-validation-for="Partner" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Customer" class="control-label"></label>
                        <input asp-for="Customer" autocomplete="off" class="form-control" />
                        <span asp-validation-for="Customer" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <label asp-for="StartDate" for="example-date-input" class="col-4 col-form-label">Start Date</label>
                        <div class="col-10">
                            <input asp-for="StartDate" class="form-control" type="date"  id="example-date-input">
                        </div>
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>

                    <!--<div class="form-group">
        <label asp-for="Tasks" class="control-label"></label>
        <input asp-for="Tasks" class="form-control" />
        <span asp-validation-for="Tasks" class="text-danger"></span>
    </div>-->

                    <div class="text-center">
                        <div class="row">
                            <div class="text-center">
                                <div style="width: 12rem;">
                                    <input type="submit" value="Create New Project" class="btn btn-success" />
                                </div>
                            </div>

                            <div class="text-center">
                                <div class="btn btn-danger text-center" style="width: 11rem;">
                                    <a asp-action="Index">Cancel</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ICONEXT/Views/projects/Delete.cshtml
@model ICONEXT.Models.project

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="text-center">
    <h1>Delete Project</h1>
</div>
<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="row">
        
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Partner)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Partner)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Customer)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProjID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ICONEXT/Views/projects/Details.cshtml
@model ICONEXT.Models.project

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="text-center">
    <h1>Details Project</h1>
</div>


    <div class="card  col-7">

        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Partner)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Partner)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Customer)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Customer)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.StartDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.StartDate)
            </dd>
        </dl>
    </div>

<div class="text-center">
    <a class="btn btn-warning"asp-action="Edit" asp-route-id="@Model.ProjID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ICONEXT/Views/projects/Edit.cshtml
@model ICONEXT.Models.project

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1>Edit Project</h1>
</div>


<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>


            <div class="form-group">
                <label asp-for="ProjID" class="control-label"></label>
                <input asp-for="ProjID" autocomplete="off" class="form-control" />
                <span asp-validation-for="ProjID" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" autocomplete="off" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Partner" class="control-label"></label>
                <input asp-for="Partner"  class="form-control" />
                <span asp-validation-for="Partner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer" class="control-label"></label>
                <input asp-for="Customer" autocomplete="off" class="form-control" />
                <span asp-validation-for="Customer" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <label asp-for="StartDate" for="example-date-input" class="col-4 col-form-label">Start Date</label>
                <div class="col-10">
                    <input asp-for="StartDate" class="form-control" type="date"  id="example-date-input">
                </div>
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>

            <!--<div class="form-group">
        <label asp-for="Tasks" class="control-label"></label>
        <input asp-for="Tasks" class="form-control" />
        <span asp-validation-for="Tasks" class="text-danger"></span>
    </div>-->


            <div class="text-center">
                <div class="row">
                    <div class="text-center">

                        <input type="submit" value="Save" class="btn btn-primary" style="width: 12rem;" />

                    </div>
                    &nbsp;&nbsp;
                    <div class="text-center">
                        <div class="btn btn-danger text-center" style="width: 11rem;">
                            <a asp-action="Index">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ICONEXT/Views/projects/Index.cshtml
@model IEnumerable<ICONEXT.Models.project>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    @foreach (var item in Model)

    {

        <div class="text-center">
            <div class="card border-info   " style="width: 18rem; margin:3px;" >
                
                    <div class="card-body">
                        @Html.DisplayFor(modelItem => item.Name)
                    </div>

                    <div class="text-center">
                        <div class="btn btn-primary text-center" style="width: 5rem;">
                            <a asp-action="ViewProject" asp-route-id="@item.ProjID">Edit</a>
                        </div>
                    </div>
                    <br>
                    <div>
                        Start Date :  @Html.DisplayFor(modelItem => item.StartDate)
                    </div>
               
            </div>



            <!-------------------------------menu dropdown------------------------------------->


            <div class="text-right">
                <div class="dropdown">
                    <!--Trigger-->
                    <a type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical" fill="currentColor"
                             xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                  d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
                        </svg>
                    </a>
                    <!--Menu-->
                    <div class="dropdown-menu dropdown-primary">
                        <a class="dropdown-item" asp-action="Edit" asp-route-id="@item.ProjID">Edit</a>
                        <a class="dropdown-item" asp-action="Details" asp-route-id="@item.ProjID">Details</a>
                        <a class="dropdown-item" asp-action="Delete" asp-route-id="@item.ProjID">Delete</a>

                    </div>



                </div>
            </div> &nbsp;&nbsp;&nbsp;&nbsp;

            <br>
        </div>


    }
</div>

   

<div class="text-center">
    <a asp-action="Create">
        <div class="btn btn-success text-center" style="width: 12rem;">
            Create New Project
        </div>
    </a>
</div>

ICONEXT/Views/projects/ViewProject.cshtml
@using ICONEXT;
@model ICONEXT.Models.Project_Phase


@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{
    IEnumerable<Project_Phase> displaydata = ViewData["Results"] as IEnumerable<Project_Phase>;
}

@using (Html.BeginForm("ViewProject", "Project_Phase", FormMethod.Post, new { @class = "ui large form" }))
{

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>




    <form asp-action="ViewProject">
        <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 table-responsive">
                    <div style="float:unset">
                        <a id="add_row" class="btn btn-primary addnewrow pull-left">
                            <span class="glyphicon glyphicon-plus"></span>
                            Add Tasks
                        </a>
                        &nbsp;
                        <button id="save" class="btn btn-primary ">
                            <span class="glyphicon glyphicon-ok"></span>
                            Save Changes
                        </button>

                    </div>
                    <table class="table table-bordered table-hover table-sortable " id="tab_logic">
                        <thead>
                            <tr>
                                <th class="text-center">

                                </th>
                                <th class="text-center">
                                    Tasks
                                </th>
                                <th class="text-center">
                                    Phase
                                </th>

                                <th class="text-center">
                                    StartDate
                                </th>
                                <th class="text-center">
                                    Enddate
                                </th>
                                <th class="text-center">
                                    Manpower
                                </th>
                                <th class="text-center">
                                    Role
                                </th>
                                <th class="text-center">
                                    Usage
                                </th>

                                <th class="text-center">
                                    Save
                                </th>
                                <th class="text-center">
                                    Delete
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr id='addr0' data-id="0" class="hidden">

                                <td data-name="button">
                                    <button type="button" class="btn btn-success row-addsub">Add Phase</button>
                                </td>
                                <td data-name="name">
                                    <div class="task text-center" style="width:130px;">
                                        <input asp-for="Name" autocomplete="off" class="form-control" id="Task" />
                                    </div>
                                </td>

                                <td data-name="mail">
                                </td>
                                <td data-name="desc">
                                </td>
                                <td data-name="sel">
                                </td>
                                <td data-name="sel">
                                </td>
                                <td data-name="sel">
                                </td>
                                <td data-name="sel">
                                </td>

                                <td data-name="save">
                                    <button name"save" class='btn btn-primary glyphicon glyphicon-ok row-ok'></button>
                                </td>

                                <td data-name="del ">
                                    <button name"del0" class='btn btn-danger glyphicon glyphicon-remove row-remove '></button>
                                </td>

                            </tr>
                        </tbody>
                    </table>
                    <table name="errortitle">
                    </table>


                </div>
            </div>
        </div>
    </form>

    <script>
        $(document).ready(function () {
            $("#add_row").on("click", function () {
                // Dynamic Rows Code

                // Get max row id and set new id
                var newid = 0;
                $.each($("#tab_logic tr"), function () {
                    if (parseInt($(this).data("id")) > newid) {
                        newid = parseInt($(this).data("id"));
                    }
                });
                newid++;
                var tr = $("<tr></tr>", {
                    id: "addr" + newid,
                    "data-id": newid
                });

                $("save_chang").on("click", function () {


                });

                // loop through each td and create new elements with name of newid
                $.each($("#tab_logic tbody tr:nth(0) td"), function () {
                    var cur_td = $(this);

                    var children = cur_td.children();

                    // add new td and element if it has a nane
                    if ($(this).data("name") != undefined) {
                        var td = $("<td></td>", {
                            "data-name": $(cur_td).data("name")
                        });

                        var c = $(cur_td).find($(children[0]).prop('tagName')).clone().val("");
                        c.attr("name", $(cur_td).data("name") + newid);
                        c.appendTo($(td));
                        td.appendTo($(tr));
                    } else {
                        var td = $("<td></td>", {
                            'text': $('#tab_logic tr').length
                        }).appendTo($(tr));
                    }
                });


                // add the new row
                $(tr).appendTo($('#tab_logic'));


                $(tr).find("td button.row-remove").on("click", function () {
                    $(this).closest("tr").remove();
                });

                $('#tab_logic').on('click', "td button.row-remove", function () {
                    var current = $(this).parents("tr");

                    if (current.attr('id')) {
                        // Parent
                        while (true) {
                            var next = current.next();
                            if (next.length == 0 || next.attr('id')) {
                                break;
                            }

                            next.remove();
                        }
                        current.remove();
                    } else {
                        //child
                        current.remove();
                    }
                });

                $(tr).find('td button.row-addsub').on("click", function () {
                    $("tr").has(this).after('<tr><td></td><td></td><td><input type="text"/></td><td><input type="date"/></td><td><input type="date"/></td><td></td><td></td><td><input type="text"/></td><td><button class="btn btn-primary glyphicon glyphicon-ok row-ok"></button></td><td><button class="btn btn-danger glyphicon glyphicon-remove row-remove"></button></td></tr>');
                });
            });



            // Sortable Code
            var fixHelperModified = function (e, tr) {
                var $originals = tr.children();
                var $helper = tr.clone();

                $helper.children().each(function (index) {
                    $(this).width($originals.eq(index).width())
                });

                return $helper;
            };

            $(".table-sortable tbody").sortable({
                helper: fixHelperModified
            }).disableSelection();

            $(".table-sortable thead").disableSelection();



            $("#add_row").trigger("click");
        })

    </script>

}